exports.seed = async function (knex) {
  await knex("product").insert([
    {
      name: "X-Salada",
      description: "Lanches",
      ingredient:
        "Pão de hambúrguer, hambúrguer industrial de 90 gramas ou artesanal de 130 gramas, queijo muçarela derretido na chapa, alface e tomate frescos, molho especial com cheddar e maionese.",
      price: 9,
      additional: true,
      image: "x1.png",
      promotion: false,
      pricePromotion: 0,
      category_id: 1,
      measureUnid_id: 59,
      visibleApp: true,
    },
    {
      name: "X-Salada Bacon",
      description: "Lanches",
      ingredient:
        "Pão de hambúrguer , hambúrguer industrial de 90 gramas ou artesanal de 130 gramas, fatia de bacon suculentas, queijo muçarela derretido na chapa, alface e tomate frescos, molho especial com cheddar e maionese.",
      price: 19.5,
      additional: false,
      image: "x2.png",
      promotion: false,
      pricePromotion: 0,
      category_id: 1,
      measureUnid_id: 59,
      visibleApp: true,
    },
    {
      name: "Salada EGG",
      description: "Lanches",
      ingredient:
        "Pão de hambúrguer , hambúrguer industrial de 90 gramas ou artesanal de 130 gramas, ovo, queijo muçarela derretido na chapa, alface e tomate frescos, molho especial com cheddar e maionese .",
      price: 20,
      additional: true,
      image: "x4.png",
      promotion: false,
      pricePromotion: 0,
      category_id: 1,
      measureUnid_id: 59,
      visibleApp: true,
    },
    {
      name: "EGG SALADA DUPLA CARNE",
      description: "Lanches",
      ingredient:
        "Pão de hambúrguer , 2 hambúrguer industrial de 90 gramas ou artesanal de 130 gramas, 2 ovos, queijo muçarela derretido na chapa, alface e tomate frescos, molho especial com cheddar e maionese.",
      price: 25,
      additional: true,
      image: "x3.png",
      promotion: false,
      pricePromotion: 0,
      category_id: 1,
      measureUnid_id: 59,
      visibleApp: true,
    },
    {
      name: "X-Tudo",
      description: "Lanches",
      ingredient:
        "Pão de hambúrguer ,hambúrguer industrial de 90 gramas ou artesanal de 130 gramas, fatias de bacon suculentas, ovo, apresuntado bronzeado, queijo muçarela derretido na chapa, alface e tomate frescos, molho especial com cheddar e maionese.",
      price: 35,
      additional: true,
      image: "x5.png",
      promotion: false,
      pricePromotion: 0,
      category_id: 1,
      measureUnid_id: 59,
      visibleApp: true,
    },
    {
      name: "Agua com gás",
      description: "Bebidas",
      ingredient: "",
      price: 2.5,
      additional: false,
      image: "default.png",
      promotion: false,
      pricePromotion: 0,
      category_id: 2,
      measureUnid_id: 59,
      visibleApp: true,
    },
    {
      name: "Agua sem gás",
      description: "Bebidas",
      ingredient: "",
      price: 2,
      additional: false,
      image: "default.png",
      promotion: false,
      pricePromotion: 0,
      category_id: 2,
      measureUnid_id: 59,
      visibleApp: true,
    },
    {
      name: "Sprite Lemon Fresh 500ml",
      description: "Bebidas",
      ingredient: "",
      price: 3.5,
      additional: false,
      image: "default.png",
      promotion: false,
      pricePromotion: 0,
      category_id: 2,
      measureUnid_id: 59,
      visibleApp: true,
    },
    {
      name: "Coca-Cola Lata 350ml",
      description: "Bebidas",
      ingredient: "",
      price: 4,
      additional: false,
      image: "cocacolalata350.png",
      promotion: false,
      pricePromotion: 0,
      category_id: 2,
      measureUnid_id: 59,
      visibleApp: true,
    },
    {
      name: "Cerveja SKOL lata 350ml",
      description: "Bebidas",
      ingredient: "",
      price: 4,
      additional: false,
      image: "skollatao473.png",
      promotion: false,
      pricePromotion: 0,
      category_id: 2,
      measureUnid_id: 59,
      visibleApp: true,
    },
  ]);
};
